name: Build Diagrams

on:
  push:
    paths:
      - "docs/**"
      - ".github/workflows/build-diagrams.yml"

  workflow_dispatch:

jobs:
  build-diagrams:
    name: Python
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./docs

    steps:
      - uses: actions/checkout@v5

      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "docs/pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install project
        run: uv sync --locked --all-extras --dev

      - name: Build diagrams
        run: uv run main.py

      - name: Commit and push diagrams
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/
          git diff --staged --quiet || git commit -m "chore: update architecture diagrams
          git push
