name: "Terraform CI/CD"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    outputs:
      bucket_url: ${{ steps.bucket.outputs.BUCKET_URL }}
      website_url: ${{ steps.website.outputs.WEBSITE_URL }}
      cloudfront_distribution_id: ${{ steps.cloudfront.outputs.CLOUDFRONT_DISTRIBUTION_ID }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/seagram-dev-github-actions-role
          role-session-name: github-actions
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: ./terraform
        continue-on-error: false
        timeout-minutes: 2

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        working-directory: ./terraform

      - name: Set Bucket URL
        id: bucket
        run: echo "BUCKET_URL=$(terraform output -raw bucket_url)" >> "$GITHUB_OUTPUT"
        working-directory: ./terraform

      - name: Set Website URL
        id: website
        run: echo "WEBSITE_URL=$(terraform output -raw website_url)" >> "$GITHUB_OUTPUT"
        working-directory: ./terraform

      - name: Set CloudFront Distribution ID
        id: cloudfront
        run: echo "CLOUDFRONT_DISTRIBUTION_ID=$(terraform output -raw cloudfront_distribution_id)" >> "$GITHUB_OUTPUT"
        working-directory: ./terraform

  build:
    needs: terraform
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./blog

      - name: Build
        run: pnpm run build
        working-directory: ./blog

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: blog/dist

  publish:
    needs: [terraform, build]
    name: "Publish"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/seagram-dev-github-actions-role
          role-session-name: github-actions
          aws-region: us-east-1

      - name: Sync to S3
        env:
          AWS_S3_BUCKET: ${{ needs.terraform.outputs.bucket_url }}
        run: aws s3 sync dist/ $AWS_S3_BUCKET --delete

      - name: Invalidate CloudFront
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{ needs.terraform.outputs.cloudfront_distribution_id }}
        run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*" "/"

      - name: Echo URL
        env:
          WEBSITE_URL: ${{ needs.terraform.outputs.website_url }}
        run: echo "$WEBSITE_URL" >> "$GITHUB_STEP_SUMMARY"
